### ISSUE TITLE
Replace uses of "cookbook site" with "supermarket"

### ISSUE THREAD

**Issue by robbkidd** [JFrogDev/knife-art#9]
:wave: Hallo, knife-art maintainers!

There is a looming deprecation in knife where `cookbook site` commands are being replaced by `supermarket`. The [deprecation warnings have been in there for a few months](https://github.com/chef/chef/commit/2a52b0208a4f22ff2eed04da980d9c32c175e122) and the `cookbook site` commands and classes are scheduled to be removed in Chef's next major release (v16, April 2020).

There are fixes for this already in [jasonwbarnett](https://github.com/jasonwbarnett)'s [knife-artifactory fork](https://github.com/jasonwbarnett/knife-artifactory). As @jasonwbarnett [mentioned elsewhere](https://github.com/jfrog/knife-art/issues/6#issuecomment-495299895), I am also curious about whether this gem and knife plugin is still being maintained. It looks like you've got some help!

**Comment by robbkidd** [comment]
A quick glance at things in the fork and I think these two commits sort out the deprecation:

- https://github.com/jasonwbarnett/knife-artifactory/commit/9ae050bba760bea89451a9b737b49733e6c514f8
- https://github.com/jasonwbarnett/knife-artifactory/commit/eca9bf4093259a9a9a5287494698ae63a33cae78

**Comment by Dispader** [comment]
@robbkidd @jasonwbarnett D'either of you know if a Pull has been submitted yet?  I'm not seeing one, but I'm thinking that we might want.  😁

**Comment by robbkidd** [comment]
A pull request hasn't been opened, yet. Possibly the work to create a PR was waiting on confirmation that the gem was still being maintained.

**Comment by robbkidd** [comment]
Now there's a pull request!

**Comment by robbkidd** [comment]
@Dispader A PR is open now. How's that look? If good, there might be some other improvements over on [jasonwbarnett/knife-artifactory](https://github.com/jasonwbarnett/knife-artifactory) to consider.

**Comment by Dispader** [comment]
@robbkidd It looks good here— if I could approve it, I would.  😁
